language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key: 3b2639e6-90c0-4542-8d40-41f05bee82ca
  app: teaswirll-todo
  on:
    repo: teaswirll/addressbook
    branch: todo_tasks
